/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EventsRouteImport } from './routes/events'
import { Route as InterviewsRouteImport } from './routes/interviews'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as PodcastRouteImport } from './routes/podcast'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin.route'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ESlugRouteImport } from './routes/e.$slug'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'
import { Route as PodcastApplyRouteImport } from './routes/podcast.apply'
import { Route as PodcastBookRouteImport } from './routes/podcast.book'
import { Route as ScoreQuizRouteImport } from './routes/score.quiz'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminCalendarRouteImport } from './routes/_authenticated/admin.calendar'
import { Route as AuthenticatedAdminDuplicatesRouteImport } from './routes/_authenticated/admin.duplicates'
import { Route as AuthenticatedAdminEventsRouteImport } from './routes/_authenticated/admin.events'
import { Route as AuthenticatedAdminImportRouteImport } from './routes/_authenticated/admin.import'
import { Route as AuthenticatedAdminInterviewsRouteImport } from './routes/_authenticated/admin.interviews'
import { Route as AuthenticatedAdminPipelineRouteImport } from './routes/_authenticated/admin.pipeline'
import { Route as AuthenticatedAdminPodcastRouteImport } from './routes/_authenticated/admin.podcast'
import { Route as AuthenticatedAdminQueueRouteImport } from './routes/_authenticated/admin.queue'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppBillingRouteImport } from './routes/_authenticated/app.billing'
import { Route as AuthenticatedAppScoreRouteImport } from './routes/_authenticated/app.score'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as ScoreRTokenRouteImport } from './routes/score.r.$token'
import { Route as AuthenticatedAdminPeopleIndexRouteImport } from './routes/_authenticated/admin.people.index'
import { Route as AuthenticatedAdminPeopleIdRouteImport } from './routes/_authenticated/admin.people.$id'
import { Route as AuthenticatedAdminProjectsIndexRouteImport } from './routes/_authenticated/admin.projects.index'
import { Route as AuthenticatedAdminProjectsIdRouteImport } from './routes/_authenticated/admin.projects.$id'
import { Route as AuthenticatedAppBookIndexRouteImport } from './routes/_authenticated/app.book.index'
import { Route as AuthenticatedAppBookSlugRouteImport } from './routes/_authenticated/app.book.$slug'
import { Route as AuthenticatedAppProjectsIndexRouteImport } from './routes/_authenticated/app.projects.index'
import { Route as AuthenticatedAppProjectsIdRouteImport } from './routes/_authenticated/app.projects.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewsRoute = InterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastRoute = PodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ESlugRoute = ESlugRouteImport.update({
  id: '/e/$slug',
  path: '/e/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastApplyRoute = PodcastApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => PodcastRoute,
} as any)
const PodcastBookRoute = PodcastBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => PodcastRoute,
} as any)
const ScoreQuizRoute = ScoreQuizRouteImport.update({
  id: '/score/quiz',
  path: '/score/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminCalendarRoute =
  AuthenticatedAdminCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDuplicatesRoute =
  AuthenticatedAdminDuplicatesRouteImport.update({
    id: '/duplicates',
    path: '/duplicates',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEventsRoute =
  AuthenticatedAdminEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminImportRoute =
  AuthenticatedAdminImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminInterviewsRoute =
  AuthenticatedAdminInterviewsRouteImport.update({
    id: '/interviews',
    path: '/interviews',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPipelineRoute =
  AuthenticatedAdminPipelineRouteImport.update({
    id: '/pipeline',
    path: '/pipeline',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPodcastRoute =
  AuthenticatedAdminPodcastRouteImport.update({
    id: '/podcast',
    path: '/podcast',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminQueueRoute = AuthenticatedAdminQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppBillingRoute = AuthenticatedAppBillingRouteImport.update({
  id: '/app/billing',
  path: '/app/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppScoreRoute = AuthenticatedAppScoreRouteImport.update({
  id: '/app/score',
  path: '/app/score',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/app/settings',
    path: '/app/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ScoreRTokenRoute = ScoreRTokenRouteImport.update({
  id: '/score/r/$token',
  path: '/score/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminPeopleIndexRoute =
  AuthenticatedAdminPeopleIndexRouteImport.update({
    id: '/people/',
    path: '/people/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPeopleIdRoute =
  AuthenticatedAdminPeopleIdRouteImport.update({
    id: '/people/$id',
    path: '/people/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProjectsIndexRoute =
  AuthenticatedAdminProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProjectsIdRoute =
  AuthenticatedAdminProjectsIdRouteImport.update({
    id: '/projects/$id',
    path: '/projects/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAppBookIndexRoute =
  AuthenticatedAppBookIndexRouteImport.update({
    id: '/app/book/',
    path: '/app/book/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppBookSlugRoute =
  AuthenticatedAppBookSlugRouteImport.update({
    id: '/app/book/$slug',
    path: '/app/book/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppProjectsIndexRoute =
  AuthenticatedAppProjectsIndexRouteImport.update({
    id: '/app/projects/',
    path: '/app/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppProjectsIdRoute =
  AuthenticatedAppProjectsIdRouteImport.update({
    id: '/app/projects/$id',
    path: '/app/projects/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/interviews': typeof InterviewsRoute
  '/login': typeof LoginRoute
  '/mission': typeof MissionRoute
  '/podcast': typeof PodcastRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/e/$slug': typeof ESlugRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/podcast/apply': typeof PodcastApplyRoute
  '/podcast/book': typeof PodcastBookRoute
  '/score/quiz': typeof ScoreQuizRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/admin/duplicates': typeof AuthenticatedAdminDuplicatesRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/interviews': typeof AuthenticatedAdminInterviewsRoute
  '/admin/pipeline': typeof AuthenticatedAdminPipelineRoute
  '/admin/podcast': typeof AuthenticatedAdminPodcastRoute
  '/admin/queue': typeof AuthenticatedAdminQueueRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/score': typeof AuthenticatedAppScoreRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/score/r/$token': typeof ScoreRTokenRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/admin/people/$id': typeof AuthenticatedAdminPeopleIdRoute
  '/admin/projects/$id': typeof AuthenticatedAdminProjectsIdRoute
  '/app/book/$slug': typeof AuthenticatedAppBookSlugRoute
  '/app/projects/$id': typeof AuthenticatedAppProjectsIdRoute
  '/admin/people/': typeof AuthenticatedAdminPeopleIndexRoute
  '/admin/projects/': typeof AuthenticatedAdminProjectsIndexRoute
  '/app/book/': typeof AuthenticatedAppBookIndexRoute
  '/app/projects/': typeof AuthenticatedAppProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/interviews': typeof InterviewsRoute
  '/login': typeof LoginRoute
  '/mission': typeof MissionRoute
  '/podcast': typeof PodcastRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/e/$slug': typeof ESlugRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/podcast/apply': typeof PodcastApplyRoute
  '/podcast/book': typeof PodcastBookRoute
  '/score/quiz': typeof ScoreQuizRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog': typeof BlogIndexRoute
  '/learn': typeof LearnIndexRoute
  '/services': typeof ServicesIndexRoute
  '/admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/admin/duplicates': typeof AuthenticatedAdminDuplicatesRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/interviews': typeof AuthenticatedAdminInterviewsRoute
  '/admin/pipeline': typeof AuthenticatedAdminPipelineRoute
  '/admin/podcast': typeof AuthenticatedAdminPodcastRoute
  '/admin/queue': typeof AuthenticatedAdminQueueRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/score': typeof AuthenticatedAppScoreRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/score/r/$token': typeof ScoreRTokenRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/admin/people/$id': typeof AuthenticatedAdminPeopleIdRoute
  '/admin/projects/$id': typeof AuthenticatedAdminProjectsIdRoute
  '/app/book/$slug': typeof AuthenticatedAppBookSlugRoute
  '/app/projects/$id': typeof AuthenticatedAppProjectsIdRoute
  '/admin/people': typeof AuthenticatedAdminPeopleIndexRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsIndexRoute
  '/app/book': typeof AuthenticatedAppBookIndexRoute
  '/app/projects': typeof AuthenticatedAppProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/interviews': typeof InterviewsRoute
  '/login': typeof LoginRoute
  '/mission': typeof MissionRoute
  '/podcast': typeof PodcastRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/e/$slug': typeof ESlugRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/podcast/apply': typeof PodcastApplyRoute
  '/podcast/book': typeof PodcastBookRoute
  '/score/quiz': typeof ScoreQuizRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/_authenticated/admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/_authenticated/admin/duplicates': typeof AuthenticatedAdminDuplicatesRoute
  '/_authenticated/admin/events': typeof AuthenticatedAdminEventsRoute
  '/_authenticated/admin/import': typeof AuthenticatedAdminImportRoute
  '/_authenticated/admin/interviews': typeof AuthenticatedAdminInterviewsRoute
  '/_authenticated/admin/pipeline': typeof AuthenticatedAdminPipelineRoute
  '/_authenticated/admin/podcast': typeof AuthenticatedAdminPodcastRoute
  '/_authenticated/admin/queue': typeof AuthenticatedAdminQueueRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/app/billing': typeof AuthenticatedAppBillingRoute
  '/_authenticated/app/score': typeof AuthenticatedAppScoreRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/score/r/$token': typeof ScoreRTokenRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/admin/people/$id': typeof AuthenticatedAdminPeopleIdRoute
  '/_authenticated/admin/projects/$id': typeof AuthenticatedAdminProjectsIdRoute
  '/_authenticated/app/book/$slug': typeof AuthenticatedAppBookSlugRoute
  '/_authenticated/app/projects/$id': typeof AuthenticatedAppProjectsIdRoute
  '/_authenticated/admin/people/': typeof AuthenticatedAdminPeopleIndexRoute
  '/_authenticated/admin/projects/': typeof AuthenticatedAdminProjectsIndexRoute
  '/_authenticated/app/book/': typeof AuthenticatedAppBookIndexRoute
  '/_authenticated/app/projects/': typeof AuthenticatedAppProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/community'
    | '/contact'
    | '/events'
    | '/interviews'
    | '/login'
    | '/mission'
    | '/podcast'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/blog/$slug'
    | '/e/$slug'
    | '/learn/$slug'
    | '/podcast/apply'
    | '/podcast/book'
    | '/score/quiz'
    | '/services/$slug'
    | '/blog/'
    | '/learn/'
    | '/services/'
    | '/admin/calendar'
    | '/admin/duplicates'
    | '/admin/events'
    | '/admin/import'
    | '/admin/interviews'
    | '/admin/pipeline'
    | '/admin/podcast'
    | '/admin/queue'
    | '/admin/settings'
    | '/app/billing'
    | '/app/score'
    | '/app/settings'
    | '/score/r/$token'
    | '/admin/'
    | '/app/'
    | '/admin/people/$id'
    | '/admin/projects/$id'
    | '/app/book/$slug'
    | '/app/projects/$id'
    | '/admin/people/'
    | '/admin/projects/'
    | '/app/book/'
    | '/app/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/community'
    | '/contact'
    | '/events'
    | '/interviews'
    | '/login'
    | '/mission'
    | '/podcast'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/e/$slug'
    | '/learn/$slug'
    | '/podcast/apply'
    | '/podcast/book'
    | '/score/quiz'
    | '/services/$slug'
    | '/blog'
    | '/learn'
    | '/services'
    | '/admin/calendar'
    | '/admin/duplicates'
    | '/admin/events'
    | '/admin/import'
    | '/admin/interviews'
    | '/admin/pipeline'
    | '/admin/podcast'
    | '/admin/queue'
    | '/admin/settings'
    | '/app/billing'
    | '/app/score'
    | '/app/settings'
    | '/score/r/$token'
    | '/admin'
    | '/app'
    | '/admin/people/$id'
    | '/admin/projects/$id'
    | '/app/book/$slug'
    | '/app/projects/$id'
    | '/admin/people'
    | '/admin/projects'
    | '/app/book'
    | '/app/projects'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/community'
    | '/contact'
    | '/events'
    | '/interviews'
    | '/login'
    | '/mission'
    | '/podcast'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/admin'
    | '/blog/$slug'
    | '/e/$slug'
    | '/learn/$slug'
    | '/podcast/apply'
    | '/podcast/book'
    | '/score/quiz'
    | '/services/$slug'
    | '/blog/'
    | '/learn/'
    | '/services/'
    | '/_authenticated/admin/calendar'
    | '/_authenticated/admin/duplicates'
    | '/_authenticated/admin/events'
    | '/_authenticated/admin/import'
    | '/_authenticated/admin/interviews'
    | '/_authenticated/admin/pipeline'
    | '/_authenticated/admin/podcast'
    | '/_authenticated/admin/queue'
    | '/_authenticated/admin/settings'
    | '/_authenticated/app/billing'
    | '/_authenticated/app/score'
    | '/_authenticated/app/settings'
    | '/score/r/$token'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
    | '/_authenticated/admin/people/$id'
    | '/_authenticated/admin/projects/$id'
    | '/_authenticated/app/book/$slug'
    | '/_authenticated/app/projects/$id'
    | '/_authenticated/admin/people/'
    | '/_authenticated/admin/projects/'
    | '/_authenticated/app/book/'
    | '/_authenticated/app/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  InterviewsRoute: typeof InterviewsRoute
  LoginRoute: typeof LoginRoute
  MissionRoute: typeof MissionRoute
  PodcastRoute: typeof PodcastRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ESlugRoute: typeof ESlugRoute
  LearnSlugRoute: typeof LearnSlugRoute
  ScoreQuizRoute: typeof ScoreQuizRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  LearnIndexRoute: typeof LearnIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ScoreRTokenRoute: typeof ScoreRTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interviews': {
      id: '/interviews'
      path: '/interviews'
      fullPath: '/interviews'
      preLoaderRoute: typeof InterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast': {
      id: '/podcast'
      path: '/podcast'
      fullPath: '/podcast'
      preLoaderRoute: typeof PodcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$slug': {
      id: '/e/$slug'
      path: '/e/$slug'
      fullPath: '/e/$slug'
      preLoaderRoute: typeof ESlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast/apply': {
      id: '/podcast/apply'
      path: '/apply'
      fullPath: '/podcast/apply'
      preLoaderRoute: typeof PodcastApplyRouteImport
      parentRoute: typeof PodcastRoute
    }
    '/podcast/book': {
      id: '/podcast/book'
      path: '/book'
      fullPath: '/podcast/book'
      preLoaderRoute: typeof PodcastBookRouteImport
      parentRoute: typeof PodcastRoute
    }
    '/score/quiz': {
      id: '/score/quiz'
      path: '/score/quiz'
      fullPath: '/score/quiz'
      preLoaderRoute: typeof ScoreQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/calendar': {
      id: '/_authenticated/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AuthenticatedAdminCalendarRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/duplicates': {
      id: '/_authenticated/admin/duplicates'
      path: '/duplicates'
      fullPath: '/admin/duplicates'
      preLoaderRoute: typeof AuthenticatedAdminDuplicatesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/events': {
      id: '/_authenticated/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AuthenticatedAdminEventsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/import': {
      id: '/_authenticated/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AuthenticatedAdminImportRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/interviews': {
      id: '/_authenticated/admin/interviews'
      path: '/interviews'
      fullPath: '/admin/interviews'
      preLoaderRoute: typeof AuthenticatedAdminInterviewsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pipeline': {
      id: '/_authenticated/admin/pipeline'
      path: '/pipeline'
      fullPath: '/admin/pipeline'
      preLoaderRoute: typeof AuthenticatedAdminPipelineRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/podcast': {
      id: '/_authenticated/admin/podcast'
      path: '/podcast'
      fullPath: '/admin/podcast'
      preLoaderRoute: typeof AuthenticatedAdminPodcastRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/queue': {
      id: '/_authenticated/admin/queue'
      path: '/queue'
      fullPath: '/admin/queue'
      preLoaderRoute: typeof AuthenticatedAdminQueueRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/billing': {
      id: '/_authenticated/app/billing'
      path: '/app/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AuthenticatedAppBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/score': {
      id: '/_authenticated/app/score'
      path: '/app/score'
      fullPath: '/app/score'
      preLoaderRoute: typeof AuthenticatedAppScoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/score/r/$token': {
      id: '/score/r/$token'
      path: '/score/r/$token'
      fullPath: '/score/r/$token'
      preLoaderRoute: typeof ScoreRTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/people/': {
      id: '/_authenticated/admin/people/'
      path: '/people'
      fullPath: '/admin/people/'
      preLoaderRoute: typeof AuthenticatedAdminPeopleIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/people/$id': {
      id: '/_authenticated/admin/people/$id'
      path: '/people/$id'
      fullPath: '/admin/people/$id'
      preLoaderRoute: typeof AuthenticatedAdminPeopleIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/projects/': {
      id: '/_authenticated/admin/projects/'
      path: '/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AuthenticatedAdminProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/projects/$id': {
      id: '/_authenticated/admin/projects/$id'
      path: '/projects/$id'
      fullPath: '/admin/projects/$id'
      preLoaderRoute: typeof AuthenticatedAdminProjectsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/app/book/': {
      id: '/_authenticated/app/book/'
      path: '/app/book'
      fullPath: '/app/book/'
      preLoaderRoute: typeof AuthenticatedAppBookIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/book/$slug': {
      id: '/_authenticated/app/book/$slug'
      path: '/app/book/$slug'
      fullPath: '/app/book/$slug'
      preLoaderRoute: typeof AuthenticatedAppBookSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/projects/': {
      id: '/_authenticated/app/projects/'
      path: '/app/projects'
      fullPath: '/app/projects/'
      preLoaderRoute: typeof AuthenticatedAppProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/projects/$id': {
      id: '/_authenticated/app/projects/$id'
      path: '/app/projects/$id'
      fullPath: '/app/projects/$id'
      preLoaderRoute: typeof AuthenticatedAppProjectsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminCalendarRoute: typeof AuthenticatedAdminCalendarRoute
  AuthenticatedAdminDuplicatesRoute: typeof AuthenticatedAdminDuplicatesRoute
  AuthenticatedAdminEventsRoute: typeof AuthenticatedAdminEventsRoute
  AuthenticatedAdminImportRoute: typeof AuthenticatedAdminImportRoute
  AuthenticatedAdminInterviewsRoute: typeof AuthenticatedAdminInterviewsRoute
  AuthenticatedAdminPipelineRoute: typeof AuthenticatedAdminPipelineRoute
  AuthenticatedAdminPodcastRoute: typeof AuthenticatedAdminPodcastRoute
  AuthenticatedAdminQueueRoute: typeof AuthenticatedAdminQueueRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminPeopleIdRoute: typeof AuthenticatedAdminPeopleIdRoute
  AuthenticatedAdminProjectsIdRoute: typeof AuthenticatedAdminProjectsIdRoute
  AuthenticatedAdminPeopleIndexRoute: typeof AuthenticatedAdminPeopleIndexRoute
  AuthenticatedAdminProjectsIndexRoute: typeof AuthenticatedAdminProjectsIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminCalendarRoute: AuthenticatedAdminCalendarRoute,
    AuthenticatedAdminDuplicatesRoute: AuthenticatedAdminDuplicatesRoute,
    AuthenticatedAdminEventsRoute: AuthenticatedAdminEventsRoute,
    AuthenticatedAdminImportRoute: AuthenticatedAdminImportRoute,
    AuthenticatedAdminInterviewsRoute: AuthenticatedAdminInterviewsRoute,
    AuthenticatedAdminPipelineRoute: AuthenticatedAdminPipelineRoute,
    AuthenticatedAdminPodcastRoute: AuthenticatedAdminPodcastRoute,
    AuthenticatedAdminQueueRoute: AuthenticatedAdminQueueRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminPeopleIdRoute: AuthenticatedAdminPeopleIdRoute,
    AuthenticatedAdminProjectsIdRoute: AuthenticatedAdminProjectsIdRoute,
    AuthenticatedAdminPeopleIndexRoute: AuthenticatedAdminPeopleIndexRoute,
    AuthenticatedAdminProjectsIndexRoute: AuthenticatedAdminProjectsIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAppBillingRoute: typeof AuthenticatedAppBillingRoute
  AuthenticatedAppScoreRoute: typeof AuthenticatedAppScoreRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppBookSlugRoute: typeof AuthenticatedAppBookSlugRoute
  AuthenticatedAppProjectsIdRoute: typeof AuthenticatedAppProjectsIdRoute
  AuthenticatedAppBookIndexRoute: typeof AuthenticatedAppBookIndexRoute
  AuthenticatedAppProjectsIndexRoute: typeof AuthenticatedAppProjectsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAppBillingRoute: AuthenticatedAppBillingRoute,
  AuthenticatedAppScoreRoute: AuthenticatedAppScoreRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppBookSlugRoute: AuthenticatedAppBookSlugRoute,
  AuthenticatedAppProjectsIdRoute: AuthenticatedAppProjectsIdRoute,
  AuthenticatedAppBookIndexRoute: AuthenticatedAppBookIndexRoute,
  AuthenticatedAppProjectsIndexRoute: AuthenticatedAppProjectsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PodcastRouteChildren {
  PodcastApplyRoute: typeof PodcastApplyRoute
  PodcastBookRoute: typeof PodcastBookRoute
}

const PodcastRouteChildren: PodcastRouteChildren = {
  PodcastApplyRoute: PodcastApplyRoute,
  PodcastBookRoute: PodcastBookRoute,
}

const PodcastRouteWithChildren =
  PodcastRoute._addFileChildren(PodcastRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  InterviewsRoute: InterviewsRoute,
  LoginRoute: LoginRoute,
  MissionRoute: MissionRoute,
  PodcastRoute: PodcastRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  ESlugRoute: ESlugRoute,
  LearnSlugRoute: LearnSlugRoute,
  ScoreQuizRoute: ScoreQuizRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  LearnIndexRoute: LearnIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ScoreRTokenRoute: ScoreRTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
