/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'
import { Route as ScoreQuizRouteImport } from './routes/score.quiz'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppBillingRouteImport } from './routes/_authenticated/app.billing'
import { Route as AuthenticatedAppScoreRouteImport } from './routes/_authenticated/app.score'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as ScoreRTokenRouteImport } from './routes/score.r.$token'
import { Route as AuthenticatedAppBookIndexRouteImport } from './routes/_authenticated/app.book.index'
import { Route as AuthenticatedAppBookSlugRouteImport } from './routes/_authenticated/app.book.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreQuizRoute = ScoreQuizRouteImport.update({
  id: '/score/quiz',
  path: '/score/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppBillingRoute = AuthenticatedAppBillingRouteImport.update({
  id: '/app/billing',
  path: '/app/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppScoreRoute = AuthenticatedAppScoreRouteImport.update({
  id: '/app/score',
  path: '/app/score',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/app/settings',
    path: '/app/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ScoreRTokenRoute = ScoreRTokenRouteImport.update({
  id: '/score/r/$token',
  path: '/score/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppBookIndexRoute =
  AuthenticatedAppBookIndexRouteImport.update({
    id: '/app/book/',
    path: '/app/book/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppBookSlugRoute =
  AuthenticatedAppBookSlugRouteImport.update({
    id: '/app/book/$slug',
    path: '/app/book/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/mission': typeof MissionRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/score/quiz': typeof ScoreQuizRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/learn/': typeof LearnIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/score': typeof AuthenticatedAppScoreRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/score/r/$token': typeof ScoreRTokenRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/book/$slug': typeof AuthenticatedAppBookSlugRoute
  '/app/book/': typeof AuthenticatedAppBookIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/mission': typeof MissionRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/score/quiz': typeof ScoreQuizRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/learn': typeof LearnIndexRoute
  '/services': typeof ServicesIndexRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/score': typeof AuthenticatedAppScoreRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/score/r/$token': typeof ScoreRTokenRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/book/$slug': typeof AuthenticatedAppBookSlugRoute
  '/app/book': typeof AuthenticatedAppBookIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/mission': typeof MissionRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/score/quiz': typeof ScoreQuizRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/learn/': typeof LearnIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/_authenticated/app/billing': typeof AuthenticatedAppBillingRoute
  '/_authenticated/app/score': typeof AuthenticatedAppScoreRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/score/r/$token': typeof ScoreRTokenRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/book/$slug': typeof AuthenticatedAppBookSlugRoute
  '/_authenticated/app/book/': typeof AuthenticatedAppBookIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/community'
    | '/contact'
    | '/login'
    | '/mission'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/learn/$slug'
    | '/score/quiz'
    | '/services/$slug'
    | '/learn/'
    | '/services/'
    | '/app/billing'
    | '/app/score'
    | '/app/settings'
    | '/score/r/$token'
    | '/app/'
    | '/app/book/$slug'
    | '/app/book/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/community'
    | '/contact'
    | '/login'
    | '/mission'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/learn/$slug'
    | '/score/quiz'
    | '/services/$slug'
    | '/learn'
    | '/services'
    | '/app/billing'
    | '/app/score'
    | '/app/settings'
    | '/score/r/$token'
    | '/app'
    | '/app/book/$slug'
    | '/app/book'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/community'
    | '/contact'
    | '/login'
    | '/mission'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/learn/$slug'
    | '/score/quiz'
    | '/services/$slug'
    | '/learn/'
    | '/services/'
    | '/_authenticated/app/billing'
    | '/_authenticated/app/score'
    | '/_authenticated/app/settings'
    | '/score/r/$token'
    | '/_authenticated/app/'
    | '/_authenticated/app/book/$slug'
    | '/_authenticated/app/book/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  MissionRoute: typeof MissionRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  LearnSlugRoute: typeof LearnSlugRoute
  ScoreQuizRoute: typeof ScoreQuizRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  LearnIndexRoute: typeof LearnIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ScoreRTokenRoute: typeof ScoreRTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/score/quiz': {
      id: '/score/quiz'
      path: '/score/quiz'
      fullPath: '/score/quiz'
      preLoaderRoute: typeof ScoreQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/billing': {
      id: '/_authenticated/app/billing'
      path: '/app/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AuthenticatedAppBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/score': {
      id: '/_authenticated/app/score'
      path: '/app/score'
      fullPath: '/app/score'
      preLoaderRoute: typeof AuthenticatedAppScoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/score/r/$token': {
      id: '/score/r/$token'
      path: '/score/r/$token'
      fullPath: '/score/r/$token'
      preLoaderRoute: typeof ScoreRTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/book/': {
      id: '/_authenticated/app/book/'
      path: '/app/book'
      fullPath: '/app/book/'
      preLoaderRoute: typeof AuthenticatedAppBookIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/book/$slug': {
      id: '/_authenticated/app/book/$slug'
      path: '/app/book/$slug'
      fullPath: '/app/book/$slug'
      preLoaderRoute: typeof AuthenticatedAppBookSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppBillingRoute: typeof AuthenticatedAppBillingRoute
  AuthenticatedAppScoreRoute: typeof AuthenticatedAppScoreRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppBookSlugRoute: typeof AuthenticatedAppBookSlugRoute
  AuthenticatedAppBookIndexRoute: typeof AuthenticatedAppBookIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppBillingRoute: AuthenticatedAppBillingRoute,
  AuthenticatedAppScoreRoute: AuthenticatedAppScoreRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppBookSlugRoute: AuthenticatedAppBookSlugRoute,
  AuthenticatedAppBookIndexRoute: AuthenticatedAppBookIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  MissionRoute: MissionRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  LearnSlugRoute: LearnSlugRoute,
  ScoreQuizRoute: ScoreQuizRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  LearnIndexRoute: LearnIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ScoreRTokenRoute: ScoreRTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
